# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/service/inventory/v1/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/service/inventory/v1/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(api/service/inventory/v1/inventory.proto\x12\x0cinventory.v1\x1a\x1bgoogle/protobuf/empty.proto\",\n\x0cGoodsInvInfo\x12\x0f\n\x07goodsId\x18\x01 \x01(\x05\x12\x0b\n\x03num\x18\x02 \x01(\x05\"J\n\x08SellInfo\x12-\n\tgoodsInfo\x18\x01 \x03(\x0b\x32\x1a.inventory.v1.GoodsInvInfo\x12\x0f\n\x07orderSn\x18\x02 \x01(\t2\x80\x02\n\tInventory\x12<\n\x06SetInv\x12\x1a.inventory.v1.GoodsInvInfo\x1a\x16.google.protobuf.Empty\x12\x43\n\tInvDetail\x12\x1a.inventory.v1.GoodsInvInfo\x1a\x1a.inventory.v1.GoodsInvInfo\x12\x36\n\x04Sell\x12\x16.inventory.v1.SellInfo\x1a\x16.google.protobuf.Empty\x12\x38\n\x06Reback\x12\x16.inventory.v1.SellInfo\x1a\x16.google.protobuf.EmptyB$Z\"lushop/api/service/inventory/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.service.inventory.v1.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"lushop/api/service/inventory/v1;v1'
  _globals['_GOODSINVINFO']._serialized_start=87
  _globals['_GOODSINVINFO']._serialized_end=131
  _globals['_SELLINFO']._serialized_start=133
  _globals['_SELLINFO']._serialized_end=207
  _globals['_INVENTORY']._serialized_start=210
  _globals['_INVENTORY']._serialized_end=466
# @@protoc_insertion_point(module_scope)
