# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/service/user/v1/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/service/user/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61pi/service/user/v1/user.proto\x12\x0b\x61pi.user.v1\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x0e\x43reateUserInfo\x12\x10\n\x08nickName\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\"\x82\x01\n\x10UserInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0e\n\x06mobile\x18\x03 \x01(\t\x12\x10\n\x08nickName\x18\x04 \x01(\t\x12\x10\n\x08\x62irthday\x18\x05 \x01(\x04\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\x05\"N\n\x10UserListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12+\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x1d.api.user.v1.UserInfoResponse\"%\n\x08PageInfo\x12\n\n\x02pn\x18\x01 \x01(\r\x12\r\n\x05pSize\x18\x02 \x01(\r\"\x1f\n\rMobileRequest\x12\x0e\n\x06mobile\x18\x01 \x01(\t\"\x17\n\tIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"b\n\x0eUpdateUserInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x10\n\x08\x62irthday\x18\x05 \x01(\x04\"@\n\x11PasswordCheckInfo\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x19\n\x11\x65ncryptedPassword\x18\x02 \x01(\t\" \n\rCheckResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc5\x03\n\x04User\x12J\n\nCreateUser\x12\x1b.api.user.v1.CreateUserInfo\x1a\x1d.api.user.v1.UserInfoResponse\"\x00\x12\x45\n\x0bGetUserList\x12\x15.api.user.v1.PageInfo\x1a\x1d.api.user.v1.UserListResponse\"\x00\x12N\n\x0fGetUserByMobile\x12\x1a.api.user.v1.MobileRequest\x1a\x1d.api.user.v1.UserInfoResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x16.api.user.v1.IdRequest\x1a\x1d.api.user.v1.UserInfoResponse\"\x00\x12\x43\n\nUpdateUser\x12\x1b.api.user.v1.UpdateUserInfo\x1a\x16.google.protobuf.Empty\"\x00\x12M\n\rCheckPassword\x12\x1e.api.user.v1.PasswordCheckInfo\x1a\x1a.api.user.v1.CheckResponse\"\x00\x42$\n\x0b\x61pi.user.v1P\x01Z\x13user/api/user/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.service.user.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013api.user.v1P\001Z\023user/api/user/v1;v1'
  _globals['_CREATEUSERINFO']._serialized_start=76
  _globals['_CREATEUSERINFO']._serialized_end=144
  _globals['_USERINFORESPONSE']._serialized_start=147
  _globals['_USERINFORESPONSE']._serialized_end=277
  _globals['_USERLISTRESPONSE']._serialized_start=279
  _globals['_USERLISTRESPONSE']._serialized_end=357
  _globals['_PAGEINFO']._serialized_start=359
  _globals['_PAGEINFO']._serialized_end=396
  _globals['_MOBILEREQUEST']._serialized_start=398
  _globals['_MOBILEREQUEST']._serialized_end=429
  _globals['_IDREQUEST']._serialized_start=431
  _globals['_IDREQUEST']._serialized_end=454
  _globals['_UPDATEUSERINFO']._serialized_start=456
  _globals['_UPDATEUSERINFO']._serialized_end=554
  _globals['_PASSWORDCHECKINFO']._serialized_start=556
  _globals['_PASSWORDCHECKINFO']._serialized_end=620
  _globals['_CHECKRESPONSE']._serialized_start=622
  _globals['_CHECKRESPONSE']._serialized_end=654
  _globals['_USER']._serialized_start=657
  _globals['_USER']._serialized_end=1110
# @@protoc_insertion_point(module_scope)
