# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.service.user.v1 import user_pb2 as api_dot_service_dot_user_dot_v1_dot_user__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/service/user/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/api.user.v1.User/CreateUser',
                request_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.CreateUserInfo.SerializeToString,
                response_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.FromString,
                _registered_method=True)
        self.GetUserList = channel.unary_unary(
                '/api.user.v1.User/GetUserList',
                request_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.PageInfo.SerializeToString,
                response_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserListResponse.FromString,
                _registered_method=True)
        self.GetUserByMobile = channel.unary_unary(
                '/api.user.v1.User/GetUserByMobile',
                request_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.MobileRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.FromString,
                _registered_method=True)
        self.GetUserById = channel.unary_unary(
                '/api.user.v1.User/GetUserById',
                request_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.IdRequest.SerializeToString,
                response_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/api.user.v1.User/UpdateUser',
                request_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UpdateUserInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CheckPassword = channel.unary_unary(
                '/api.user.v1.User/CheckPassword',
                request_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.PasswordCheckInfo.SerializeToString,
                response_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.CheckResponse.FromString,
                _registered_method=True)


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByMobile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.CreateUserInfo.FromString,
                    response_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.SerializeToString,
            ),
            'GetUserList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserList,
                    request_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.PageInfo.FromString,
                    response_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserListResponse.SerializeToString,
            ),
            'GetUserByMobile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByMobile,
                    request_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.MobileRequest.FromString,
                    response_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.SerializeToString,
            ),
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.IdRequest.FromString,
                    response_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.UpdateUserInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CheckPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPassword,
                    request_deserializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.PasswordCheckInfo.FromString,
                    response_serializer=api_dot_service_dot_user_dot_v1_dot_user__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.user.v1.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.user.v1.User', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.user.v1.User/CreateUser',
            api_dot_service_dot_user_dot_v1_dot_user__pb2.CreateUserInfo.SerializeToString,
            api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.user.v1.User/GetUserList',
            api_dot_service_dot_user_dot_v1_dot_user__pb2.PageInfo.SerializeToString,
            api_dot_service_dot_user_dot_v1_dot_user__pb2.UserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByMobile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.user.v1.User/GetUserByMobile',
            api_dot_service_dot_user_dot_v1_dot_user__pb2.MobileRequest.SerializeToString,
            api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.user.v1.User/GetUserById',
            api_dot_service_dot_user_dot_v1_dot_user__pb2.IdRequest.SerializeToString,
            api_dot_service_dot_user_dot_v1_dot_user__pb2.UserInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.user.v1.User/UpdateUser',
            api_dot_service_dot_user_dot_v1_dot_user__pb2.UpdateUserInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.user.v1.User/CheckPassword',
            api_dot_service_dot_user_dot_v1_dot_user__pb2.PasswordCheckInfo.SerializeToString,
            api_dot_service_dot_user_dot_v1_dot_user__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
